Add tab size specification
Mango0x45/center pull request #5
Opened 2022-10-02 16:44 UTC by nothing-c

Properly, this time.

2022-10-03 08:17 UTC, Mango0x45 requested changes

2022-10-03 08:17 UTC, Mango0x45 commented on center.c
> +				errx(EXIT_FAILURE, "Tab size must be >0");
I think we could just require the tab size to be non-negative.  It would be weird to have a tab size of 0 but I see no real reason why it shouldn't be allowed.

2022-10-03 08:17 UTC, Mango0x45 commented on center.c
> +	while ((opt = getopt(argc, argv, ":elswt:")) != -1) {
`getopt()` requires you to put a colon after each flag that takes an argument.  Since both `-w` and `-t` take an argument, this should be `:elsw:t:`

2022-10-03 08:17 UTC, Mango0x45 commented on center.c
> +			break;
Most of this code seems to be the same as the handling of `-w`.  Perhaps it should be moved into it's own function or generalized in some way?

2022-10-03 08:17 UTC, Mango0x45 commented on center.c
> +			if (errno == ERANGE || width > INT_MAX)
Should be `tabsize > INT_MAX`, not `width > INT_MAX`

2022-10-03 08:17 UTC, Mango0x45 commented on center.c
> +long tabsize;
This should default to a length of 8 (so `long tabsize = 8;`)

2022-10-03 21:33 UTC, nothing-c commented on center.c
> +			break;
Maybe. Are there other number-taking options in the pipeline?

2022-10-03 21:55 UTC, Mango0x45 commented on center.c
> +			break;
Well right now theres `-w` and `-t`

2022-10-03 21:57 UTC, Mango0x45 commented
For the most part, this should be fine to merge.  The only thing is I would rather we used the term „tab width“ instead of „tab size“.

2022-10-03 22:37 UTC, Mango0x45 approved these changes

2022-10-03 22:37 UTC, Mango0x45 commented
Great!  If you can resolve the merge conflict then I can merge this into master.

2022-10-04 18:27 UTC, nothing-c commented
Conflict resolved.

2022-10-04 21:41 UTC, Mango0x45 requested changes

2022-10-04 21:41 UTC, Mango0x45 commented on center.c
> +				warnx("Potential overflow of given tab size");
You need to add a `break;` after this line to avoid falling through to the `-l` case

2022-10-04 22:20 UTC, merged